import type {
    GridPulseBoxOptions,
    GridPulseConnectionOptions,
    GridPulseCrosshairOptions,
    GridPulseDetectionOptions,
    GridPulseEffectOptions,
    GridPulseGridOptions,
    GridPulseHudOptions,
    GridPulseInteractionOptions,
    GridPulseLabelOptions,
    GridPulseMediaOptions,
    GridPulseMotionOptions,
    GridPulseRenderingOptions,
    GridPulseThemeOptions,
} from "./GridPulseOptionTypes"

/**
 * Shipped defaults. Every value a consumer does not override comes from here,
 * so this file is the single reference for the component's out-of-the-box look
 * and timing. Tests and measurement tools read it rather than restating values.
 */

export const DEFAULT_MEDIA: GridPulseMediaOptions = {
    type: "auto",
    crossOrigin: "anonymous",
    objectFit: "cover",
    positionX: 0.5,
    positionY: 0.5,
    mirror: false,
    videoAutoPlay: true,
    videoLoop: true,
    videoMuted: true,
    videoPlaybackRate: 1,
}

export const DEFAULT_DETECTION: GridPulseDetectionOptions = {
    mode: "auto",
    pointCount: 5,
    minDistance: 0.16,
    edgeSensitivity: 0.7,
    personBias: 0.75,
    centerBias: 0.15,
    detailEdgeWeight: 0.76,
    detailTextureWeight: 0.52,
    personSkinWeight: 0.78,
    autoPersonWeight: 0.68,
    modeDiversity: 0.16,
    focusX: 0.5,
    focusY: 0.5,
    focusRadius: 0.72,
    focusStrength: 0,
    temporalSmoothing: 0.42,
    preservePointIds: true,
    trackingMode: "stable",
    trackingMaxDistance: 0.24,
    trackingMaxLostFrames: 4,
    trackingSmoothing: 0.58,
    trackingVelocitySmoothing: 0.68,
    trackingPrediction: true,
    trackingScoreWeight: 0.08,
    clickSearchRadius: 0.28,
    seed: 7187,
    manualPoints: [],
    customDetector: null,
    mobilePointLimit: 3,
}

export const DEFAULT_GRID: GridPulseGridOptions = {
    visible: true,
    // Registration crosses, not ruled lines: the default backdrop reads as an
    // instrument calibration field. `lines` remains one option away.
    style: "crosses",
    animate: true,
    animation: "hybrid",
    speed: 1,
    driftX: 10,
    driftY: 6,
    pulseStrength: 0.2,
    scanWidth: 0.18,
    scanStrength: 0.34,
    scanDirection: "diagonal",
    spacing: 150,
    color: "#ffffff",
    // Crosses cover far fewer pixels than lines, so they carry more opacity.
    opacity: 0.4,
    lineWidth: 1,
    dash: [3, 6],
    subdivisions: 2,
}

export const DEFAULT_CONNECTIONS: GridPulseConnectionOptions = {
    visible: true,
    topology: "leaders",
    pointTopology: "nearest",
    color: "#ffffff",
    opacity: 0.7,
    lineWidth: 1,
    dash: [2, 6],
    tickMarks: true,
    tickSpacing: 34,
    tickLength: 6,
    pointSize: 10,
    pointShape: "square",
    pulse: true,
    animation: "hybrid",
    drawDuration: 420,
    stagger: 55,
    flowSpeed: 0.16,
    flowLength: 42,
    flowOpacity: 0.72,
}

export const DEFAULT_CROSSHAIR: GridPulseCrosshairOptions = {
    visible: true,
    followPointer: true,
    followMode: "smooth",
    followResponse: 95,
    snapThreshold: 0.35,
    returnToCenter: false,
    color: "#ffffff",
    opacity: 0.55,
    lineWidth: 1,
    dash: [],
    radius: 23,
    showCoordinates: true,
    coordinateStyle: "latlon",
    font: "10px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    labelOffsetX: 30,
    labelOffsetY: -12,
}

export const DEFAULT_BOXES: GridPulseBoxOptions = {
    visible: true,
    layout: "callout",
    trackingScale: 1,
    trackingSafeTop: 24,
    trackingSafeBottom: 24,
    trackingMinGap: 12,
    trackingParallax: 0,
    width: 112,
    height: 112,
    mobileScale: 0.76,
    zoom: 2.5,
    gap: 64,
    padding: 8,
    borderColor: "#ffffff",
    borderOpacity: 0.5,
    borderWidth: 1,
    radius: 0,
    backgroundColor: "#050505",
    shadow: "0 12px 42px rgba(0,0,0,.42)",
    cornerBrackets: true,
    cornerLength: 16,
    cornerWidth: 2,
    cornerOpacity: 1,
    scanSweep: true,
    scanColor: "#ffffff",
    scanOpacity: 0.72,
    scanWidth: 1,
    scanDirection: "vertical",
    scanDuration: 0,
    scanDelay: 0,
    scanMode: "loop",
    scanEasing: "linear",
    scanBandWidth: 18,
    scanSoftness: 0.5,
    scanTrail: 0.35,
    avoidOverlap: true,
    clampToBounds: true,
    animation: "acquire",
    animationStagger: 52,
    lockDuration: 150,
    unfoldDuration: 320,
    mediaDelay: 120,
    settleDuration: 420,
    ambientBreath: 0.006,
}

export const DEFAULT_LABELS: GridPulseLabelOptions = {
    visible: true,
    template: "TGT {index} · {score}",
    scorePrecision: 2,
    coordinateStyle: "inherit",
    timeFormat: "clock",
    timecodeFps: 30,
    color: "#ffffff",
    background: "rgba(0,0,0,.54)",
    borderColor: "rgba(255,255,255,.36)",
    borderWidth: 1,
    font: "9px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    paddingX: 5,
    paddingY: 3,
    offsetX: 5,
    offsetY: 5,
    uppercase: true,
    letterSpacing: 0.085,
}

export const DEFAULT_HUD: GridPulseHudOptions = {
    visible: true,
    color: "#ffffff",
    opacity: 0.85,
    frameBrackets: true,
    frameInset: 10,
    frameLength: 26,
    frameWidth: 1.5,
    edgeTicks: true,
    edgeTickSpacing: 40,
    edgeTickLength: 5,
    readout: true,
    readoutPrimary: "SCAN {mode} · TGT {n}",
    readoutSecondary: "{w}×{h} · {fps} FPS",
    statusDot: true,
    font: "10px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    letterSpacing: 0.14,
    sweep: true,
    sweepDuration: 900,
    sweepOpacity: 0.55,
}

export const DEFAULT_EFFECT: GridPulseEffectOptions = {
    type: "none",
    scope: "media",
    intensity: 1,
    tint: "#f4f4f4",
    background: "#030303",
    pixelSize: 9,
    pixelGap: 0,
    pixelLevels: 0,
    pixelSampling: "average",
    pixelAnchor: "image",
    pixelShape: "square",
    pixelRadius: 0.22,
    bitmapScale: 3,
    bitmapThreshold: 0.52,
    bitmapMethod: "ordered",
    bitmapPalette: "none",
    bitmapMatrix: "bayer4",
    bitmapLevels: 2,
    bitmapAnchor: "image",
    bitmapDotShape: "square",
    bitmapGamma: 1,
    codeCellSize: 8,
    codeCharacters: " .:-=+*#%@01<>/\\{}[]ABCDEFGHJKLMNPQRSTUVWXYZ",
    codeOpacity: 0.92,
    codeSampling: "average",
    codeAnchor: "image",
    codeColorMode: "tint",
    codeEdgeWeight: 0.34,
    codeThreshold: 0.055,
    codeGamma: 0.88,
    codeBackgroundOpacity: 1,
    xrayContrast: 1.45,
    xrayBrightness: 1.06,
    xrayInvert: true,
    xrayEdgeStrength: 3.6,
    xrayEdgeThreshold: 0.045,
    xrayGlow: 1,
    xrayPreserveDetail: 0,
    thermalPalette: "ironbow",
    thermalContrast: 1.3,
    thermalBrightness: 1,
    thermalGamma: 0.9,
    refreshRate: 12,
}

export const DEFAULT_INTERACTION: GridPulseInteractionOptions = {
    activation: "hover",
    clickToRescan: true,
    rescanOnEnter: true,
    deactivateOnLeave: true,
    autoRescanInterval: 0,
    mobileAlwaysOn: false,
    touchBehavior: "auto",
    touchReleaseDelay: 120,
    touchRescan: true,
    touchCrosshair: true,
    cursor: "crosshair",
    keyboardControls: true,
    leaveDelay: 90,
    enterDuration: 180,
    exitDuration: 220,
    rescanTransition: "fade",
    rescanExitDuration: 150,
    rescanGap: 35,
    rescanEnterDuration: 240,
}

export const DEFAULT_MOTION: GridPulseMotionOptions = {
    revealDuration: 420,
    stagger: 90,
    scanDuration: 1450,
    pulseDuration: 1600,
    easing: "easeOut",
    respectReducedMotion: true,
    reducedMotionReveal: "instant",
}

export const DEFAULT_THEME: GridPulseThemeOptions = {
    background: "#000000",
    overlayWhenInactive: false,
    inactiveOpacity: 0,
    // Default ON since v3.0.0-rc.3: with it off, the white default chrome is
    // near-invisible on light media — measured on a real white-background
    // photo (docs/captures/media/lilies-default-before.jpg). Global mode keeps
    // the per-frame cost of the default path low; regional stays opt-in.
    adaptiveChrome: true,
    chromeLight: "#ffffff",
    chromeDark: "#050505",
    chromeSampleRadius: 9,
    chromeMinContrast: 4.5,
    chromeSpatialMode: "global",
    chromeZoneColumns: 3,
    chromeZoneRows: 3,
    chromeHalo: true,
    chromeHaloWidth: 1,
    chromeHaloOpacity: 0.28,
    adaptiveChromeElements: true,
    chromeContrastCompensation: 0.78,
    chromeBusySimplification: 0.52,
    chromeAdaptiveGlow: true,
}

export const DEFAULT_RENDERING: GridPulseRenderingOptions = {
    maxFps: 60,
    staticImageFps: 30,
    inactiveFps: 4,
    dprCap: 2,
    demandDriven: true,
    useVideoFrameCallback: true,
    pauseWhenOffscreen: true,
}

export const GRID_PULSE_SCAN_DEFAULTS = {
    media: DEFAULT_MEDIA,
    detection: DEFAULT_DETECTION,
    grid: DEFAULT_GRID,
    connections: DEFAULT_CONNECTIONS,
    crosshair: DEFAULT_CROSSHAIR,
    boxes: DEFAULT_BOXES,
    labels: DEFAULT_LABELS,
    hud: DEFAULT_HUD,
    effect: DEFAULT_EFFECT,
    interaction: DEFAULT_INTERACTION,
    motion: DEFAULT_MOTION,
    rendering: DEFAULT_RENDERING,
    theme: DEFAULT_THEME,
} as const
